apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fullstackapp
data:
  #SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service.fullstackapp.svc.cluster.local:3306/mydb
  SPRING_PROFILES_ACTIVE: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstackapp
  labels:
    app: fullstack
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fullstack
        tier: backend
    spec:
      containers:
        - name: backend
          image: basmaoueslati/fullstackproject:backend-{{ version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstackapp
  labels:
    app: fullstack
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: fullstack
    tier: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
