apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project5
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
        - name: backend
          image: busybox:latest  # placeholder؛ Jenkins سيضبطها بـ set image
          command: ['sh', '-c', 'echo waiting-for-image && sleep 3600']
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: SPRING_DATASOURCE_URL } }
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { configMapKeyRef: { name: app-config, key: SPRING_DATASOURCE_USERNAME } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: mysql-secret, key: mysql-password } }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 40
            periodSeconds: 20
