apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <YOUR_DOCKER_USERNAME>/demo-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mydb?useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack-demo
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
