apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project5
spec:
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
