apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-fullstack-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: fullstack.com   # <-- هنا اسم الدومين
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-frontend
            port:
              number: 80
      - path: /api/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-backend
            port:
              number: 8080
