apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-ingress
  namespace: fullstack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: fullstack.com
      http:
        paths:
          - path: /customers(/|$)(.*)     # يلتقط أي شيء يبدأ بـ /customers
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /                       # الباقي للفرونت
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
