apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
  namespace: fullstack
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 5Gi  
  hostPath:
    path: /mnt/data/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  namespace: fullstack
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
