apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: mydb
          volumeMounts:
            - name: data-volume    
              mountPath: /data 
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fullstack
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
