apiVersion: v1
kind: PersistentVolume
metadata:
  name: m-pv
  namespace: fullstack
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 5Gi  
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m-pvc
  namespace: fullstack
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
