- hosts: localhost
  tasks:
    - name: Build backend Docker image
      community.docker.docker_image:
        name: "{{ lookup('env','BACKEND_IMAGE') }}"
        tag: latest
        source: build
        build:
          path: "{{ lookup('env','WORKSPACE') }}/demo"

    - name: Build frontend Docker image (API points to service inside cluster)
      community.docker.docker_image:
        name: "{{ lookup('env','FRONTEND_IMAGE') }}"
        tag: latest
        source: build
        build:
          path: "{{ lookup('env','WORKSPACE') }}/frontend"
          args:
            API_URL: "http://demo-backend:8080"
