- hosts: localhost
  tasks:
    - name: Login to Docker registry
      community.docker.docker_login:
        username: "{{ lookup('env','DOCKER_USER') }}"
        password: "{{ lookup('env','DOCKER_PASS') }}"

    - name: Push backend image
      community.docker.docker_image:
        name: "{{ lookup('env','BACKEND_IMAGE') }}"
        push: yes

    - name: Push frontend image
      community.docker.docker_image:
        name: "{{ lookup('env','FRONTEND_IMAGE') }}"
        push: yes
