---
- hosts: localhost
  connection: local
  vars:
    build_number: "{{ lookup('env','BUILD_NUMBER') | default('dev', true) }}"
    workspace: "{{ lookup('env','WORKSPACE') | default(playbook_dir ~ '/..', true) }}"
    backend_image: "nouraa253/demo-backend:{{ build_number }}"
    frontend_image: "nouraa253/demo-frontend:{{ build_number }}"

  tasks:
    - name: Build backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: build
        build:
          path: "{{ workspace }}/demo"
          pull: yes

    - name: Build frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: build
        build:
          path: "{{ workspace }}/frontend"
          pull: yes
