- name: Deploy fullstack on Kubernetes
  hosts: local
  gather_facts: false
  vars:
    repo_root: "{{ playbook_dir | dirname }}"

  tasks:
    # MySQL
    - command: kubectl get deployment mysql
      register: mysql_deploy
      failed_when: false
    - command: kubectl delete deployment mysql
      when: mysql_deploy.rc == 0
    - command: kubectl get service mysql
      register: mysql_svc
      failed_when: false
    - command: kubectl delete service mysql
      when: mysql_svc.rc == 0
    - command: kubectl apply -f {{ repo_root }}/k8s/mysql-deployment.yaml

    # Backend
    - command: kubectl get deployment demo-backend
      register: be_deploy
      failed_when: false
    - command: kubectl delete deployment demo-backend
      when: be_deploy.rc == 0
    - command: kubectl get service demo-backend
      register: be_svc
      failed_when: false
    - command: kubectl delete service demo-backend
      when: be_svc.rc == 0
    - command: kubectl apply -f {{ repo_root }}/k8s/backend-deployment.yaml

    # Frontend
    - command: kubectl get deployment demo-frontend
      register: fe_deploy
      failed_when: false
    - command: kubectl delete deployment demo-frontend
      when: fe_deploy.rc == 0
    - command: kubectl get service demo-frontend
      register: fe_svc
      failed_when: false
    - command: kubectl delete service demo-frontend
      when: fe_svc.rc == 0
    - command: kubectl apply -f {{ repo_root }}/k8s/frontend-deployment.yaml
