---
- name: Push Docker Image
  hosts: localhost
  connection: local
  vars:
    backend-image: "nouraa253/demo-backend"
    frontend_image: "nouraa253/demo-frontend"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push existing Docker image
      community.docker.docker_image:
        name: "{{ backend-image }}"
        source: local  
        push: yes
        state: present
        
    - name: Push existing Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: local  
        push: yes
        state: present

